### ISSUE TITLE
Internal Exception Caused by KillAuraEntity

### ISSUE THREAD

**Issue by UnrealPixel** [Photon-GitHub/AACAdditionPro#141]
Players get disconnected with the message: 

`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 6`

I disabled every plugin and when I disabled AACAdditionPro it stopped.
I use ProtocolLib 4.3.0
Server version is Spigot 1.8.8 latest build.

**Comment by ItzSomebody** [comment]
Try using ProtocolLib 4.2.0

**Comment by UnrealPixel** [comment]
Already used that before at hope for a fix but that dit not work.

**Comment by Janmm14** [comment]
Client version?

**Comment by UnrealPixel** [comment]
The server is 1.8 - 1.12.x
I used 1.11.2

**Comment by UnrealPixel** [comment]
Anybody still here? I am still getting this error/bug?

**Comment by Photon-GitHub** [comment]
Please add the full logs of your server and my plugin.

**Comment by UnrealPixel** [comment]
`[18:09:16] [Server thread/INFO]: Starting minecraft server version 1.8.8
[18:09:16] [Server thread/INFO]: Loading properties
[18:09:16] [Server thread/INFO]: Default game type: SURVIVAL
[18:09:17] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[18:09:17] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:09:17] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:09:17] [Server thread/INFO]: Debug logging is disabled
[18:09:17] [Server thread/INFO]: Generating keypair
[18:09:17] [Server thread/INFO]: Starting Minecraft server on *:25568
[18:09:17] [Server thread/INFO]: Using epoll channel type
[18:09:17] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[18:09:18] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[18:09:18] [Server thread/INFO]: [CrazyCrates] Loading CrazyCrates v1.7.3.3
[18:09:18] [Server thread/INFO]: [ObsidianBreaker] Loading ObsidianBreaker v2.1
[18:09:18] [Server thread/INFO]: [MobMerge] Loading MobMerge v1.0.5-SNAPSHOT
[18:09:18] [Server thread/INFO]: [GroupManager] Loading GroupManager v2.0.1-b332
[18:09:18] [Server thread/INFO]: [AgarthaLib] Loading AgarthaLib vMysthoria
[18:09:18] [Server thread/INFO]: [PlugMan] Loading PlugMan v2.1.4
[18:09:18] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v1.2.0
[18:09:18] [Server thread/INFO]: [ViaVersion] ViaVersion 1.2.0 is now loaded, injecting!
[18:09:18] [Server thread/INFO]: [NametagEdit] Loading NametagEdit v4.1.7
[18:09:18] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[18:09:18] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.3.0
[18:09:19] [Server thread/INFO]: [MassiveCore] Loading MassiveCore v2.13.1
[18:09:19] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.1.2;e38d98d
[18:09:19] [Server thread/INFO]: [MyItems] Loading MyItems vMysthoria
[18:09:19] [Server thread/INFO]: [AAC] Loading AAC v3.3.2
[18:09:19] [Server thread/INFO]: [Essentials] Loading Essentials v2.0.1-b488
[18:09:19] [Server thread/INFO]: [CrazyAuctions] Loading CrazyAuctions v1.2.4
[18:09:19] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.0.1-b514
[18:09:19] [Server thread/INFO]: [AACAdditionPro] Loading AACAdditionPro v3.2.3
[18:09:19] [Server thread/INFO]: [PlayerVaults] Loading PlayerVaults v3.6.0-SNAPSHOT-b210
[18:09:19] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.2.6
[18:09:19] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b514
[18:09:19] [Server thread/INFO]: [Factions] Loading Factions v2.13.1
[18:09:19] [Server thread/INFO]: [CrazyEnvoy] Loading CrazyEnvoy v1.2.8.3
[18:09:19] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[18:09:19] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[18:09:19] [Server thread/INFO]: [Vault] [Permission] GroupManager found: Waiting
[18:09:19] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[18:09:19] [Server thread/INFO]: [Vault] [Chat] GroupManager found: Waiting
[18:09:19] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[18:09:19] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.3.0
[18:09:19] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[18:09:19] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v2.13.1
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m=== ENABLE START ===[m
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mLoading Cachefile datas...[m
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mLoading Onlineplayer datas...[m
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mLoading Registry datas...[m
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mSaving Cachefile...[m
[18:09:19] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mSetup of IdUtil took [0;35;1m20[0;33;1mms.[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsBasics[0;33;1m set to [0;35;1mMinecraft 1.7.10+ [1_7_R4+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsBoard[0;33;1m set to [0;35;1mMinecraft 1.8.0+ [1_8_R1+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsChat[0;33;1m set to [0;35;1mMinecraft 1.8.3+ [1_8_R2+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsEntityDamageEvent[0;33;1m set to [0;35;1mMinecraft 1.7.10+ [1_7_R4+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsEntityGet[0;33;1m set to [0;35;1mMinecraft 1.8.0+ [1_8_R1+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsItemStackCreate[0;33;1m set to [0;35;1mMinecraft 1.7.10+ [1_7_R4+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsItemStackTooltip[0;33;1m set to [0;35;1mMinecraft 1.8.0+ [1_8_R1+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsPermissions[0;33;1m set to [0;35;1mMinecraft 1.7.10+ [1_7_R4+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsPlayerInventoryCreate[0;33;1m set to [0;35;1mMinecraft 1.7.10+ [1_7_R4+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mNmsSkullMeta[0;33;1m set to [0;35;1mMinecraft 1.8.0+ [1_8_R1+][m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;32;1mIntegration Activated [0;35;1mIntegrationVault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinEvent[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinActionbar[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinActual[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinCommand[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinDisplayName[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinGamemode[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinInventory[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinKick[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinLog[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinMassiveCraftPremium[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinMessage[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinModification[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinPlayed[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinSenderPs[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinTeleport[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinTitle[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinVisibility[0;33;1m set to [0;35;1mDefault[m
[18:09:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mMixinWorld[0;33;1m set to [0;35;1mDefault[m
[18:09:21] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.13.1[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m1895ms[0;33;1m) ===[m
[18:09:21] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[18:09:21] [Server thread/INFO]: Preparing level "world"
[18:09:21] [Server thread/INFO]: -------- World Settings For [world] --------
[18:09:21] [Server thread/INFO]: Mob Spawn Range: 4
[18:09:21] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:09:21] [Server thread/INFO]: Random Lighting Updates: false
[18:09:21] [Server thread/INFO]: Structure Info Saving: true
[18:09:21] [Server thread/INFO]: Sending up to 10 chunks per packet
[18:09:21] [Server thread/INFO]: Max Entity Collisions: 8
[18:09:21] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[18:09:21] [Server thread/INFO]: Max TNT Explosions: 100
[18:09:21] [Server thread/INFO]: Anti X-Ray: true
[18:09:21] [Server thread/INFO]: 	Engine Mode: 1
[18:09:21] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:09:21] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[18:09:21] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:09:21] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:09:21] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:09:21] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:09:21] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:09:21] [Server thread/INFO]: View Distance: 10
[18:09:21] [Server thread/INFO]: Item Despawn Rate: 6000
[18:09:21] [Server thread/INFO]: Item Merge Radius: 2.5
[18:09:21] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:09:21] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:09:21] [Server thread/INFO]: Chunks to Grow per Tick: 650
[18:09:21] [Server thread/INFO]: Clear tick list: false
[18:09:21] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:09:21] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[18:09:21] [Server thread/INFO]: Mob Spawn Range: 4
[18:09:21] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:09:21] [Server thread/INFO]: Random Lighting Updates: false
[18:09:21] [Server thread/INFO]: Structure Info Saving: true
[18:09:21] [Server thread/INFO]: Sending up to 10 chunks per packet
[18:09:21] [Server thread/INFO]: Max Entity Collisions: 8
[18:09:21] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[18:09:21] [Server thread/INFO]: Max TNT Explosions: 100
[18:09:21] [Server thread/INFO]: Anti X-Ray: true
[18:09:21] [Server thread/INFO]: 	Engine Mode: 1
[18:09:21] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:09:21] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[18:09:21] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:09:21] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:09:21] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:09:21] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:09:21] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:09:21] [Server thread/INFO]: View Distance: 10
[18:09:21] [Server thread/INFO]: Item Despawn Rate: 6000
[18:09:21] [Server thread/INFO]: Item Merge Radius: 2.5
[18:09:21] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:09:21] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:09:21] [Server thread/INFO]: Chunks to Grow per Tick: 650
[18:09:21] [Server thread/INFO]: Clear tick list: false
[18:09:21] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:09:21] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[18:09:21] [Server thread/INFO]: Mob Spawn Range: 4
[18:09:21] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:09:21] [Server thread/INFO]: Random Lighting Updates: false
[18:09:21] [Server thread/INFO]: Structure Info Saving: true
[18:09:21] [Server thread/INFO]: Sending up to 10 chunks per packet
[18:09:21] [Server thread/INFO]: Max Entity Collisions: 8
[18:09:21] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[18:09:21] [Server thread/INFO]: Max TNT Explosions: 100
[18:09:21] [Server thread/INFO]: Anti X-Ray: true
[18:09:21] [Server thread/INFO]: 	Engine Mode: 1
[18:09:21] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:09:21] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[18:09:21] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:09:21] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:09:21] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[18:09:21] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:09:21] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:09:21] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:09:21] [Server thread/INFO]: View Distance: 10
[18:09:21] [Server thread/INFO]: Item Despawn Rate: 6000
[18:09:21] [Server thread/INFO]: Item Merge Radius: 2.5
[18:09:21] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:09:21] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:09:21] [Server thread/INFO]: Chunks to Grow per Tick: 650
[18:09:21] [Server thread/INFO]: Clear tick list: false
[18:09:21] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:09:21] [Server thread/INFO]: Preparing start region for level 0 (Seed: -3187543255712285859)
[18:09:22] [Server thread/INFO]: Preparing spawn area: 65%
[18:09:22] [Server thread/INFO]: Preparing start region for level 1 (Seed: -3187543255712285859)
[18:09:23] [Server thread/INFO]: Preparing start region for level 2 (Seed: -3187543255712285859)
[18:09:23] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.8-SNAPSHOT;cd4729f
[18:09:23] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[18:09:23] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[18:09:23] [Server thread/INFO]: [CrazyCrates] Enabling CrazyCrates v1.7.3.3
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Loading all crate information...
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Loading Crazy.yml information....
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Crazy.yml has been loaded.
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Loading Classic.yml information....
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Classic.yml has been loaded.
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Loading Galactic.yml information....
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Galactic.yml has been loaded.
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Loading Basic.yml information....
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> Basic.yml has been loaded.
[18:09:24] [Server thread/INFO]: [Crazy Crates]>> All crate information has been loaded.
[18:09:24] [Server thread/INFO]: [ObsidianBreaker] Enabling ObsidianBreaker v2.1
[18:09:24] [Server thread/INFO]: [ObsidianBreaker] Using NMS version v1_8_R3
[18:09:24] [Server thread/INFO]: [MobMerge] Enabling MobMerge v1.0.5-SNAPSHOT
[18:09:24] [Server thread/INFO]: [GroupManager] Enabling GroupManager v2.0.1-b332
[18:09:24] [Server thread/INFO]: GroupManager - INFO - World Found: world
[18:09:24] [Server thread/INFO]: GroupManager - INFO - Superperms support enabled.
[18:09:24] [Server thread/INFO]: GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
[18:09:24] [Server thread/INFO]: GroupManager - INFO - Backups will be retained for 24 hours!
[18:09:24] [Server thread/INFO]: GroupManager version 2.0.1-b332 is enabled!
[18:09:24] [Server thread/INFO]: WEPIF: GroupManager detected! Using GroupManager for permissions.
[18:09:24] [Server thread/INFO]: [Vault][Permission] GroupManager hooked.
[18:09:24] [Server thread/INFO]: [Vault][Chat] GroupManager - Chat hooked.
[18:09:24] [Server thread/INFO]: [AgarthaLib] Enabling AgarthaLib vMysthoria
[18:09:24] [Server thread/INFO]: [PlugMan] Enabling PlugMan v2.1.4
[18:09:24] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v1.2.0
[18:09:24] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.1.7
[18:09:24] [Server thread/INFO]: [NametagEdit] Found GroupManager! Hooking in.
[18:09:24] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.1.2;e38d98d
[18:09:25] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[18:09:25] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[18:09:25] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[18:09:25] [Server thread/INFO]: [WorldGuard] Loading region data...
[18:09:25] [Server thread/INFO]: [MyItems] Enabling MyItems vMysthoria
[18:09:25] [Server thread/INFO]: [AAC] Enabling AAC v3.3.2
[18:09:25] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b488
[18:09:25] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsChat to the same version.
[18:09:25] [Server thread/WARN]: [Essentials] §4Version mismatch! Please update EssentialsSpawn to the same version.
[18:09:25] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[18:09:25] [Server thread/INFO]: [Essentials] Using legacy item data provider as spawn egg provider.
[18:09:25] [Server thread/INFO]: [Essentials] Using legacy potion meta provider as potion meta provider.
[18:09:26] [Server thread/INFO]: Using locale en_US
[18:09:26] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[18:09:26] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[18:09:26] [Server thread/INFO]: [Essentials] Using Vault based permissions (GroupManager)
[18:09:26] [Server thread/INFO]: [CrazyAuctions] Enabling CrazyAuctions v1.2.4
[18:09:26] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.0.1-b514
[18:09:26] [Server thread/WARN]: §4Version mismatch! Please update all Essentials jars to the same version.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Enabling AACAdditionPro v3.2.3
[18:09:26] [Thread-67/INFO]: [AAC] A new version of AAC is available!
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Enabling plugin...
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Heuristic-Addition has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] LogBot has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-BetterSprinting was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-5zig was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-Forge was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-LabyMod was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-LiteLoader was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-Schematica was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-Vape has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] ClientControl-WorldDownloader has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] AutoFish is not compatible with the server-version.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] AutoPotion is not compatible with the server-version.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] EqualRotation has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Esp has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Fastswitch has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Freecam has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] InventoryChat was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] InventoryHeuristics was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] InventoryHit has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] InventoryMove has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] InventoryRotation has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] KillauraEntity has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] MultiInteraction has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Pingspoof has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Scaffold has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Skinblinker has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Teaming was chosen not to be enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] Tower has been enabled.
[18:09:26] [Server thread/INFO]: [AACAdditionPro] AACAdditionPro Version 3.2.3 enabled
[18:09:26] [Server thread/INFO]: [PlayerVaults] Enabling PlayerVaults v3.6.0-SNAPSHOT-b210
[18:09:26] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.2.6
[18:09:26] [Server thread/INFO]: [HolographicDisplays] Found ProtocolLib, using new version.
[18:09:26] [Server thread/INFO]: [HolographicDisplays] Enabled player relative placeholders with ProtocolLib.
[18:09:27] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b514
[18:09:27] [Server thread/WARN]: §4Version mismatch! Please update all Essentials jars to the same version.
[18:09:27] [Server thread/INFO]: [Factions] Enabling Factions v2.13.1
[18:09:27] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.13.1[0;36;22m] [0;33;1m=== ENABLE START ===[m
[18:09:27] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.13.1[0;36;22m] [0;33;1m[0;32;1mIntegration Activated [0;35;1mIntegrationSpigot[m
[18:09:27] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.13.1[0;36;22m] [0;33;1m[0;32;1mIntegration Activated [0;35;1mIntegrationWorldGuard[m
[18:09:27] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.13.1[0;36;22m] [0;33;1m[0;33;1mMixin [0;35;1mPowerMixin[0;33;1m set to [0;35;1mDefault[m
[18:09:27] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.13.1[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m976ms[0;33;1m) ===[m
[18:09:27] [Server thread/INFO]: [CrazyEnvoy] Enabling CrazyEnvoy v1.2.8.3
[18:09:28] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:09:28] [Server thread/INFO]: Done (7.196s)! For help, type "help" or "?"
[18:09:28] [Server thread/INFO]: [PlayerVaults] ** Vaults have already been converted to UUIDs. If this is incorrect, shutdown your server and rename the plugins/PlayerVaults/uuidvaults directory.
[18:09:28] [Craft Scheduler Thread - 8/INFO]: [PlayerVaults] We didn't find an update!
[18:09:28] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x(47)
[18:09:28] [Craft Scheduler Thread - 12/INFO]: [PlugMan] No update was found.
[18:09:28] [Server thread/INFO]: GroupManager - INFO - Bukkit Permissions Updated!
[18:09:28] [Craft Scheduler Thread - 8/INFO]: [Vault] Checking for Updates ... 
[18:09:28] [Server thread/WARN]: [ViaVersion] There is a newer version available: 1.3.0, you're on: 1.2.0
[18:09:28] [Craft Scheduler Thread - 8/INFO]: [Vault] No new version available
[18:09:28] [Server thread/INFO]: [AAC] Beginning Enable...
[18:09:28] [Server thread/INFO]: [AAC] Checking config file...
[18:09:28] [Server thread/INFO]: [AAC] (CheckManager) Enabling check chat.Spam
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Hitbox
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Fastbow
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.FightSpeed
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Check combat.Knockback is disabled
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Regen
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.FastUse
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Killaura
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Heuristics
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.BadPackets
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Speed
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Phase
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Fly
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.NoFall
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Jesus
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check movement.Derp
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check combat.Criticals
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.FastBreak
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.FastPlace
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Nuker
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.NoSwing
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Interact
[18:09:29] [Server thread/INFO]: [AAC] (CheckManager) Enabling check world.Velocity
[18:09:30] [Server thread/INFO]: [AAC] (CheckManager) Enabling check MovementManager
[18:09:30] [Server thread/INFO]: [AAC] Starting API...
[18:09:30] [Server thread/INFO]: [AAC] AAC has been enabled.
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Loading all crate preview inventories...
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Loading Crazy preview....
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Crazy loaded.
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Loading Classic preview....
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Classic loaded.
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Loading Galactic preview....
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Galactic loaded.
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Loading Basic preview....
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> Basic loaded.
[18:09:30] [Server thread/INFO]: [Crazy Crates]>> All crate previews have been loaded.
`

This is the startup log.

`[12:38:21.603] koala_beer55 failed KillauraEntity (hit the Killaura-Bot) | Vl: 1 | TPS: 19.93 | Ping: 28
[12:38:21.606] koala_beer55 failed KillauraEntity (hit the Killaura-Bot) | Vl: 2 | TPS: 19.93 | Ping: 28
[15:04:12.392] AACAdditionPro disabled.
[15:04:12.393]  
[15:04:37.27] Enabling plugin...
[15:04:37.298] Heuristic-Addition has been enabled.
[15:04:37.30] LogBot has been enabled.
[15:04:37.36] ClientControl-BetterSprinting was chosen not to be enabled.
[15:04:37.36] ClientControl-5zig was chosen not to be enabled.
[15:04:37.361] ClientControl-Forge was chosen not to be enabled.
[15:04:37.361] ClientControl-LabyMod was chosen not to be enabled.
[15:04:37.362] ClientControl-LiteLoader was chosen not to be enabled.
[15:04:37.363] ClientControl-Schematica was chosen not to be enabled.
[15:04:37.368] ClientControl-Vape has been enabled.
[15:04:37.371] ClientControl-WorldDownloader has been enabled.
[15:04:37.373] AutoFish is not compatible with the server-version.
[15:04:37.374] AutoPotion is not compatible with the server-version.
[15:04:37.375] EqualRotation has been enabled.
[15:04:37.379] Esp has been enabled.
[15:04:37.381] Fastswitch has been enabled.
[15:04:37.382] Freecam has been enabled.
[15:04:37.383] InventoryChat was chosen not to be enabled.
[15:04:37.384] InventoryHeuristics was chosen not to be enabled.
[15:04:37.385] InventoryHit has been enabled.
[15:04:37.388] InventoryMove has been enabled.
[15:04:37.388] InventoryRotation has been enabled.
[15:04:37.393] KillauraEntity has been enabled.
[15:04:37.395] MultiInteraction has been enabled.
[15:04:37.398] Pingspoof has been enabled.
[15:04:37.399] Scaffold has been enabled.
[15:04:37.40] Skinblinker has been enabled.
[15:04:37.401] Teaming was chosen not to be enabled.
[15:04:37.402] Tower has been enabled.
[15:09:15.28] AACAdditionPro disabled.
[15:09:15.281]  
[15:09:39.947] Enabling plugin...
[15:09:39.972] Heuristic-Addition has been enabled.
[15:09:39.973] LogBot has been enabled.
[15:09:40.027] ClientControl-BetterSprinting was chosen not to be enabled.
[15:09:40.028] ClientControl-5zig was chosen not to be enabled.
[15:09:40.029] ClientControl-Forge was chosen not to be enabled.
[15:09:40.029] ClientControl-LabyMod was chosen not to be enabled.
[15:09:40.03] ClientControl-LiteLoader was chosen not to be enabled.
[15:09:40.03] ClientControl-Schematica was chosen not to be enabled.
[15:09:40.034] ClientControl-Vape has been enabled.
[15:09:40.034] ClientControl-WorldDownloader has been enabled.
[15:09:40.035] AutoFish is not compatible with the server-version.
[15:09:40.036] AutoPotion is not compatible with the server-version.
[15:09:40.037] EqualRotation has been enabled.
[15:09:40.04] Esp has been enabled.
[15:09:40.041] Fastswitch has been enabled.
[15:09:40.045] Freecam has been enabled.
[15:09:40.046] InventoryChat was chosen not to be enabled.
[15:09:40.046] InventoryHeuristics was chosen not to be enabled.
[15:09:40.047] InventoryHit has been enabled.
[15:09:40.051] InventoryMove has been enabled.
[15:09:40.052] InventoryRotation has been enabled.
[15:09:40.059] KillauraEntity has been enabled.
[15:09:40.061] MultiInteraction has been enabled.
[15:09:40.063] Pingspoof has been enabled.
[15:09:40.065] Scaffold has been enabled.
[15:09:40.066] Skinblinker has been enabled.
[15:09:40.067] Teaming was chosen not to be enabled.
[15:09:40.068] Tower has been enabled.
[15:11:49.536] AACAdditionPro disabled.
[15:11:49.536]  
[15:12:15.056] Enabling plugin...
[15:12:15.083] Heuristic-Addition has been enabled.
[15:12:15.085] LogBot has been enabled.
[15:12:15.144] ClientControl-BetterSprinting was chosen not to be enabled.
[15:12:15.145] ClientControl-5zig was chosen not to be enabled.
[15:12:15.145] ClientControl-Forge was chosen not to be enabled.
[15:12:15.146] ClientControl-LabyMod was chosen not to be enabled.
[15:12:15.146] ClientControl-LiteLoader was chosen not to be enabled.
[15:12:15.146] ClientControl-Schematica was chosen not to be enabled.
[15:12:15.149] ClientControl-Vape has been enabled.
[15:12:15.149] ClientControl-WorldDownloader has been enabled.
[15:12:15.15] AutoFish is not compatible with the server-version.
[15:12:15.151] AutoPotion is not compatible with the server-version.
[15:12:15.152] EqualRotation has been enabled.
[15:12:15.155] Esp has been enabled.
[15:12:15.157] Fastswitch has been enabled.
[15:12:15.158] Freecam has been enabled.
[15:12:15.158] InventoryChat was chosen not to be enabled.
[15:12:15.159] InventoryHeuristics was chosen not to be enabled.
[15:12:15.16] InventoryHit has been enabled.
[15:12:15.174] InventoryMove has been enabled.
[15:12:15.175] InventoryRotation has been enabled.
[15:12:15.183] KillauraEntity has been enabled.
[15:12:15.185] MultiInteraction has been enabled.
[15:12:15.187] Pingspoof has been enabled.
[15:12:15.188] Scaffold has been enabled.
[15:12:15.188] Skinblinker has been enabled.
[15:12:15.189] Teaming was chosen not to be enabled.
[15:12:15.192] Tower has been enabled.
[18:08:27.44] koala_beer55 failed KillauraEntity (hit the Killaura-Bot) | Vl: 1 | TPS: 19.92 | Ping: 36
[18:08:28.71] koala_beer55 failed KillauraEntity (hit the Killaura-Bot) | Vl: 1 | TPS: 19.96 | Ping: 34
[18:09:03.378] AACAdditionPro disabled.
[18:09:03.379]  
[18:09:26.694] Enabling plugin...
[18:09:26.712] Heuristic-Addition has been enabled.
[18:09:26.714] LogBot has been enabled.
[18:09:26.76] ClientControl-BetterSprinting was chosen not to be enabled.
[18:09:26.761] ClientControl-5zig was chosen not to be enabled.
[18:09:26.762] ClientControl-Forge was chosen not to be enabled.
[18:09:26.762] ClientControl-LabyMod was chosen not to be enabled.
[18:09:26.763] ClientControl-LiteLoader was chosen not to be enabled.
[18:09:26.764] ClientControl-Schematica was chosen not to be enabled.
[18:09:26.768] ClientControl-Vape has been enabled.
[18:09:26.769] ClientControl-WorldDownloader has been enabled.
[18:09:26.771] AutoFish is not compatible with the server-version.
[18:09:26.771] AutoPotion is not compatible with the server-version.
[18:09:26.773] EqualRotation has been enabled.
[18:09:26.779] Esp has been enabled.
[18:09:26.78] Fastswitch has been enabled.
[18:09:26.782] Freecam has been enabled.
[18:09:26.782] InventoryChat was chosen not to be enabled.
[18:09:26.786] InventoryHeuristics was chosen not to be enabled.
[18:09:26.788] InventoryHit has been enabled.
[18:09:26.792] InventoryMove has been enabled.
[18:09:26.792] InventoryRotation has been enabled.
[18:09:26.799] KillauraEntity has been enabled.
[18:09:26.801] MultiInteraction has been enabled.
[18:09:26.803] Pingspoof has been enabled.
[18:09:26.807] Scaffold has been enabled.
[18:09:26.808] Skinblinker has been enabled.
[18:09:26.809] Teaming was chosen not to be enabled.
[18:09:26.813] Tower has been enabled.
`

**Comment by Photon-GitHub** [comment]
Please do not just post them here. Logs should be posted via pastebin or hastebin.

**Comment by UnrealPixel** [comment]
Your plugin its log: https://hastebin.com/oganeqorer.vbs

Server startup log: https://hastebin.com/okigaxukat.vbs

**Comment by d4d3boss** [comment]
I did test ... it would seem to be CHECK ESP.

I have disabled the ESP check and I no longer have problems!

**Comment by CeIebrimbor** [comment]
> I did test ... it would seem to be CHECK ESP.
> 
> I have disabled the ESP check and I no longer have problems!

Please report back if this changes.

**Comment by UnrealPixel** [comment]
Bug is fixed this was it! Thank you all so much!

**Comment by Photon-GitHub** [comment]
Please provide the **full** server log, not just the startup log. Moreover is your startup log formatted in just one line and therefore it is unreadable.

**Comment by UnrealPixel** [comment]
Wow... Okay so I just crashed again. I will provide the server log again.

https://hastebin.com/vefuwafanu.md
It actually gives an error at the bottom. Saying something with the out of bounds. That is also the error I am getting in the client.

**Comment by Photon-GitHub** [comment]
I guess the error originates from KillauraEntity, albeit I don’t know why this is instantly crashing the client right now, might be a specific setup causing it.

**Comment by UnrealPixel** [comment]
Okay... So uhm... Is it my config that is causing this error? Or actually something in your plugin that is giving the error? Either way my questuon is: Is this fixable.?

**Comment by Photon-GitHub** [comment]
You should maybe disable KillauraEntity for now. I will try to fix this.

**Comment by Photon-GitHub** [comment]
Should be fixed in 3.2.4

**Comment by TheIronMinerLv** [comment]
I would like to reopen this as the problem still occurs. I updated AACAdditionPro to 3.2.4, Protocollib 4.2.0, but with the "ESP" turned on, I got kicked (like a "crash", as in this issue) when I ran into places where ESP would hide me from other players..

**Comment by UnrealPixel** [comment]
I haven't tried it yet so I will try if the update has worked for me within a few minutes

**Comment by UnrealPixel** [comment]
Still bugged. I get disconnected again!

**Comment by Photon-GitHub** [comment]
Can you please post the stacktrace with the new version here?
I wonder why you are instantly disconnected, noone else ever reported that problem.

**Comment by Photon-GitHub** [comment]
@UnrealPixel Please post the stacktrace with the latest version.

**Comment by TheIronMinerLv** [comment]
How can I post a stacktrace? I have the same problem..

**Comment by ItzSomebody** [comment]
Stacktrace = big spammy error you get in console

**Comment by TheIronMinerLv** [comment]
There are no errors in console..

**Comment by UnrealPixel** [comment]
Jup same here no errors...

**Comment by Janmm14** [comment]
client log?

**Comment by Photon-GitHub** [comment]
Please report back the client log.

**Comment by Photon-GitHub** [comment]
Please report back if this is still valid.

**Comment by Photon-GitHub** [comment]
This is a known bug which appears due to the ViaVersion issue over the range of 1.8.8 - 1.12.2.
As stated on my overview KillauraEntity is only stable for 1.8.8 servers or 1.10 - 1.12.2 servers.
I cannot fix this without a tremendous amount of work, thank Mojang for changing the whole protocol.
